name: Update Products

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node scripts/update.js

      - name: Guardar cambios
        run: |
          git config --global user.name "NextFuXion Bot"
          git config --global user.email "bot@nextfuxion.local"

          git add productos.json

          git commit -m "Actualizar catalogo" || echo "Sin cambios"

          git push
