name: Update Products

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Mostrar versión Node
        run: node -v

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar lector
        run: node scripts/update.js

      - name: Guardar cambios
        run: |
          git config user.name "NextFuXion Bot"
          git config user.email "bot@nextfuxion.local"

          git add productos.json

          git commit -m "Actualizar catalogo" || echo "Sin cambios"

          git push
