name: Update Products

on:
  workflow_dispatch:

jobs:

  update:

    runs-on:
      ubuntu-latest

    steps:

    - uses:
      actions/checkout@v4

    - uses:
      actions/setup-node@v4

      with:
        node-version: 20

    - name:
      ejecutar lector

      run: |
        node scripts/update.js

    - name:
      guardar

      run: |

        git config --global user.name "NextFuXion"

        git config --global user.email "bot@nextfuxion.local"

        git add productos.json

        git commit -m "catalog update" || echo "sin cambios"

        git push
